### ISSUE TITLE
VertexHeightNoise

### ISSUE THREAD

**Issue by DeltaDizzy** [kopernicuswiki/wiki#18]

**Comment by democat3457** [comment]
Shouldn't you just create one issue and list all the TODO PQSMods there, as well as the KEX TODOs?

**Comment by DeltaDizzy** [comment]
I guess I created a progress bar for nothing then.

**Comment by democat3457** [comment]
Well, probably. It is, after all, easier to look at the issue page than the cluttered project page. Also, I think issues do give a progress bar if you have a checklist.

**Comment by DeltaDizzy** [comment]
It's a very subtle one thats very hard to see against the background. Also, you dont have to go to the project screen to see its (colorized) progress bar.

**Comment by democat3457** [comment]
But then you're left with a bunch of issues that have no description and are just there to be on the Project page. (Isn't there a way to just make a textbox instead of using issues?)

**Comment by democat3457** [comment]
https://github.com/kopernicuswiki/wiki/projects/1#card-25155089 like this.
