### ISSUE TITLE
Modular Scatter

### ISSUE THREAD

**Issue by DeltaDizzy** [kopernicuswiki/wiki#24]
General Approach will be the same as for KEx/PQSMods (new folder inside main/)
- [x] Heat Emitter
- [x] Light Emitter
- [x] Scatter Colliders
- [x] SeaLevelScatter
- [x] Landing Page (w/ general description maybe?)

**Comment by democat3457** [comment]
Will do when I get home

**Comment by democat3457** [comment]
Still ain't entirely done yet
