### ISSUE TITLE
Add enumerations to data types page

### ISSUE THREAD

**Issue by DeltaDizzy** [kopernicuswiki/wiki#28]

**Comment by democat3457** [comment]
All enums, or the definition of enum?

**Comment by DeltaDizzy** [comment]
I was thinking of the former, but both might be good.

**Comment by democat3457** [comment]
Well some enums are from KSP, some are from Unity, and only a few are from Kopernicus.

**Comment by DeltaDizzy** [comment]
We should put ones that are relevant to planet modding, regardless of the source.
