### ISSUE TITLE
redo ScaledVersion/Material

### ISSUE THREAD

**Issue by DeltaDizzy** [kopernicuswiki/wiki#36]

**Comment by democat3457** [comment]
wdym redo

**Comment by DeltaDizzy** [comment]
I mean redo it from scratch. It is nowhere near our current standards. Main Issues:
1. Subtitle
2. "very complex"
3. Example layout doesn't follow the pattern (which I would like to get followed more often)
```
@Kopernicus
{
    Body
    {
        SubNode
        {
            InnerSubNode
            {
                 // stuff
            }
        }
    }
}
```
4. Some properties could use better explanations

**Comment by democat3457** [comment]
Well it's quite complex because there are so many Material loaders that share common keys

**Comment by democat3457** [comment]
And all according to the type of body

**Comment by democat3457** [comment]
Also I thought the example layout was supposed to be
```md
ParentNode
{
    Node
    {
        key = value

        SubNode
        {
            ...
        }
    }
}
